/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoneOfGeniusCodeRouteImport } from './routes/zone-of-genius-code'
import { Route as VoiceLibraryRouteImport } from './routes/voice-library'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RareBreedOperatingManualRouteImport } from './routes/rare-breed-operating-manual'
import { Route as MetamorphosisRouteImport } from './routes/metamorphosis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GrantAccessRouteImport } from './routes/grant-access'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TenXLeapIndexRouteImport } from './routes/ten-x-leap.index'
import { Route as RareBreedClubIndexRouteImport } from './routes/rare-breed-club.index'
import { Route as PrisonBreakIndexRouteImport } from './routes/prison-break.index'
import { Route as OperatingManualIndexRouteImport } from './routes/operating-manual.index'
import { Route as LeapIndexRouteImport } from './routes/leap.index'
import { Route as DashIndexRouteImport } from './routes/dash.index'
import { Route as TenXLeapUnlockRouteImport } from './routes/ten-x-leap.unlock'
import { Route as TenXLeapReviewRouteImport } from './routes/ten-x-leap.review'
import { Route as TenXLeapModuleRouteImport } from './routes/ten-x-leap.$module'
import { Route as RareBreedClubBuilderRouteImport } from './routes/rare-breed-club.$builder'
import { Route as PrisonBreakModuleRouteImport } from './routes/prison-break.$module'
import { Route as LeapWeeklyAuditRouteImport } from './routes/leap.weekly-audit'
import { Route as LeapUpdatesRouteImport } from './routes/leap.updates'
import { Route as LeapOsRouteImport } from './routes/leap.os'
import { Route as LeapDecisionFilterRouteImport } from './routes/leap.decision-filter'
import { Route as LeapConstitutionRouteImport } from './routes/leap.constitution'
import { Route as LeapInstallationsIndexRouteImport } from './routes/leap.installations.index'
import { Route as LeapInstallationsIdRouteImport } from './routes/leap.installations.$id'

const ZoneOfGeniusCodeRoute = ZoneOfGeniusCodeRouteImport.update({
  id: '/zone-of-genius-code',
  path: '/zone-of-genius-code',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceLibraryRoute = VoiceLibraryRouteImport.update({
  id: '/voice-library',
  path: '/voice-library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RareBreedOperatingManualRoute =
  RareBreedOperatingManualRouteImport.update({
    id: '/rare-breed-operating-manual',
    path: '/rare-breed-operating-manual',
    getParentRoute: () => rootRouteImport,
  } as any)
const MetamorphosisRoute = MetamorphosisRouteImport.update({
  id: '/metamorphosis',
  path: '/metamorphosis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantAccessRoute = GrantAccessRouteImport.update({
  id: '/grant-access',
  path: '/grant-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TenXLeapIndexRoute = TenXLeapIndexRouteImport.update({
  id: '/ten-x-leap/',
  path: '/ten-x-leap/',
  getParentRoute: () => rootRouteImport,
} as any)
const RareBreedClubIndexRoute = RareBreedClubIndexRouteImport.update({
  id: '/rare-breed-club/',
  path: '/rare-breed-club/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrisonBreakIndexRoute = PrisonBreakIndexRouteImport.update({
  id: '/prison-break/',
  path: '/prison-break/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatingManualIndexRoute = OperatingManualIndexRouteImport.update({
  id: '/operating-manual/',
  path: '/operating-manual/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapIndexRoute = LeapIndexRouteImport.update({
  id: '/leap/',
  path: '/leap/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/dash/',
  path: '/dash/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenXLeapUnlockRoute = TenXLeapUnlockRouteImport.update({
  id: '/ten-x-leap/unlock',
  path: '/ten-x-leap/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const TenXLeapReviewRoute = TenXLeapReviewRouteImport.update({
  id: '/ten-x-leap/review',
  path: '/ten-x-leap/review',
  getParentRoute: () => rootRouteImport,
} as any)
const TenXLeapModuleRoute = TenXLeapModuleRouteImport.update({
  id: '/ten-x-leap/$module',
  path: '/ten-x-leap/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const RareBreedClubBuilderRoute = RareBreedClubBuilderRouteImport.update({
  id: '/rare-breed-club/$builder',
  path: '/rare-breed-club/$builder',
  getParentRoute: () => rootRouteImport,
} as any)
const PrisonBreakModuleRoute = PrisonBreakModuleRouteImport.update({
  id: '/prison-break/$module',
  path: '/prison-break/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapWeeklyAuditRoute = LeapWeeklyAuditRouteImport.update({
  id: '/leap/weekly-audit',
  path: '/leap/weekly-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapUpdatesRoute = LeapUpdatesRouteImport.update({
  id: '/leap/updates',
  path: '/leap/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapOsRoute = LeapOsRouteImport.update({
  id: '/leap/os',
  path: '/leap/os',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapDecisionFilterRoute = LeapDecisionFilterRouteImport.update({
  id: '/leap/decision-filter',
  path: '/leap/decision-filter',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapConstitutionRoute = LeapConstitutionRouteImport.update({
  id: '/leap/constitution',
  path: '/leap/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapInstallationsIndexRoute = LeapInstallationsIndexRouteImport.update({
  id: '/leap/installations/',
  path: '/leap/installations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapInstallationsIdRoute = LeapInstallationsIdRouteImport.update({
  id: '/leap/installations/$id',
  path: '/leap/installations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRoute
  '/grant-access': typeof GrantAccessRoute
  '/login': typeof LoginRoute
  '/metamorphosis': typeof MetamorphosisRoute
  '/rare-breed-operating-manual': typeof RareBreedOperatingManualRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/voice-library': typeof VoiceLibraryRoute
  '/zone-of-genius-code': typeof ZoneOfGeniusCodeRoute
  '/leap/constitution': typeof LeapConstitutionRoute
  '/leap/decision-filter': typeof LeapDecisionFilterRoute
  '/leap/os': typeof LeapOsRoute
  '/leap/updates': typeof LeapUpdatesRoute
  '/leap/weekly-audit': typeof LeapWeeklyAuditRoute
  '/prison-break/$module': typeof PrisonBreakModuleRoute
  '/rare-breed-club/$builder': typeof RareBreedClubBuilderRoute
  '/ten-x-leap/$module': typeof TenXLeapModuleRoute
  '/ten-x-leap/review': typeof TenXLeapReviewRoute
  '/ten-x-leap/unlock': typeof TenXLeapUnlockRoute
  '/dash/': typeof DashIndexRoute
  '/leap/': typeof LeapIndexRoute
  '/operating-manual/': typeof OperatingManualIndexRoute
  '/prison-break/': typeof PrisonBreakIndexRoute
  '/rare-breed-club/': typeof RareBreedClubIndexRoute
  '/ten-x-leap/': typeof TenXLeapIndexRoute
  '/leap/installations/$id': typeof LeapInstallationsIdRoute
  '/leap/installations/': typeof LeapInstallationsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/grant-access': typeof GrantAccessRoute
  '/login': typeof LoginRoute
  '/metamorphosis': typeof MetamorphosisRoute
  '/rare-breed-operating-manual': typeof RareBreedOperatingManualRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/voice-library': typeof VoiceLibraryRoute
  '/zone-of-genius-code': typeof ZoneOfGeniusCodeRoute
  '/leap/constitution': typeof LeapConstitutionRoute
  '/leap/decision-filter': typeof LeapDecisionFilterRoute
  '/leap/os': typeof LeapOsRoute
  '/leap/updates': typeof LeapUpdatesRoute
  '/leap/weekly-audit': typeof LeapWeeklyAuditRoute
  '/prison-break/$module': typeof PrisonBreakModuleRoute
  '/rare-breed-club/$builder': typeof RareBreedClubBuilderRoute
  '/ten-x-leap/$module': typeof TenXLeapModuleRoute
  '/ten-x-leap/review': typeof TenXLeapReviewRoute
  '/ten-x-leap/unlock': typeof TenXLeapUnlockRoute
  '/dash': typeof DashIndexRoute
  '/leap': typeof LeapIndexRoute
  '/operating-manual': typeof OperatingManualIndexRoute
  '/prison-break': typeof PrisonBreakIndexRoute
  '/rare-breed-club': typeof RareBreedClubIndexRoute
  '/ten-x-leap': typeof TenXLeapIndexRoute
  '/leap/installations/$id': typeof LeapInstallationsIdRoute
  '/leap/installations': typeof LeapInstallationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRoute
  '/grant-access': typeof GrantAccessRoute
  '/login': typeof LoginRoute
  '/metamorphosis': typeof MetamorphosisRoute
  '/rare-breed-operating-manual': typeof RareBreedOperatingManualRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/voice-library': typeof VoiceLibraryRoute
  '/zone-of-genius-code': typeof ZoneOfGeniusCodeRoute
  '/leap/constitution': typeof LeapConstitutionRoute
  '/leap/decision-filter': typeof LeapDecisionFilterRoute
  '/leap/os': typeof LeapOsRoute
  '/leap/updates': typeof LeapUpdatesRoute
  '/leap/weekly-audit': typeof LeapWeeklyAuditRoute
  '/prison-break/$module': typeof PrisonBreakModuleRoute
  '/rare-breed-club/$builder': typeof RareBreedClubBuilderRoute
  '/ten-x-leap/$module': typeof TenXLeapModuleRoute
  '/ten-x-leap/review': typeof TenXLeapReviewRoute
  '/ten-x-leap/unlock': typeof TenXLeapUnlockRoute
  '/dash/': typeof DashIndexRoute
  '/leap/': typeof LeapIndexRoute
  '/operating-manual/': typeof OperatingManualIndexRoute
  '/prison-break/': typeof PrisonBreakIndexRoute
  '/rare-breed-club/': typeof RareBreedClubIndexRoute
  '/ten-x-leap/': typeof TenXLeapIndexRoute
  '/leap/installations/$id': typeof LeapInstallationsIdRoute
  '/leap/installations/': typeof LeapInstallationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/grant-access'
    | '/login'
    | '/metamorphosis'
    | '/rare-breed-operating-manual'
    | '/reset-password'
    | '/settings'
    | '/voice-library'
    | '/zone-of-genius-code'
    | '/leap/constitution'
    | '/leap/decision-filter'
    | '/leap/os'
    | '/leap/updates'
    | '/leap/weekly-audit'
    | '/prison-break/$module'
    | '/rare-breed-club/$builder'
    | '/ten-x-leap/$module'
    | '/ten-x-leap/review'
    | '/ten-x-leap/unlock'
    | '/dash/'
    | '/leap/'
    | '/operating-manual/'
    | '/prison-break/'
    | '/rare-breed-club/'
    | '/ten-x-leap/'
    | '/leap/installations/$id'
    | '/leap/installations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/grant-access'
    | '/login'
    | '/metamorphosis'
    | '/rare-breed-operating-manual'
    | '/reset-password'
    | '/settings'
    | '/voice-library'
    | '/zone-of-genius-code'
    | '/leap/constitution'
    | '/leap/decision-filter'
    | '/leap/os'
    | '/leap/updates'
    | '/leap/weekly-audit'
    | '/prison-break/$module'
    | '/rare-breed-club/$builder'
    | '/ten-x-leap/$module'
    | '/ten-x-leap/review'
    | '/ten-x-leap/unlock'
    | '/dash'
    | '/leap'
    | '/operating-manual'
    | '/prison-break'
    | '/rare-breed-club'
    | '/ten-x-leap'
    | '/leap/installations/$id'
    | '/leap/installations'
  id:
    | '__root__'
    | '/admin'
    | '/grant-access'
    | '/login'
    | '/metamorphosis'
    | '/rare-breed-operating-manual'
    | '/reset-password'
    | '/settings'
    | '/voice-library'
    | '/zone-of-genius-code'
    | '/leap/constitution'
    | '/leap/decision-filter'
    | '/leap/os'
    | '/leap/updates'
    | '/leap/weekly-audit'
    | '/prison-break/$module'
    | '/rare-breed-club/$builder'
    | '/ten-x-leap/$module'
    | '/ten-x-leap/review'
    | '/ten-x-leap/unlock'
    | '/dash/'
    | '/leap/'
    | '/operating-manual/'
    | '/prison-break/'
    | '/rare-breed-club/'
    | '/ten-x-leap/'
    | '/leap/installations/$id'
    | '/leap/installations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  GrantAccessRoute: typeof GrantAccessRoute
  LoginRoute: typeof LoginRoute
  MetamorphosisRoute: typeof MetamorphosisRoute
  RareBreedOperatingManualRoute: typeof RareBreedOperatingManualRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  VoiceLibraryRoute: typeof VoiceLibraryRoute
  ZoneOfGeniusCodeRoute: typeof ZoneOfGeniusCodeRoute
  LeapConstitutionRoute: typeof LeapConstitutionRoute
  LeapDecisionFilterRoute: typeof LeapDecisionFilterRoute
  LeapOsRoute: typeof LeapOsRoute
  LeapUpdatesRoute: typeof LeapUpdatesRoute
  LeapWeeklyAuditRoute: typeof LeapWeeklyAuditRoute
  PrisonBreakModuleRoute: typeof PrisonBreakModuleRoute
  RareBreedClubBuilderRoute: typeof RareBreedClubBuilderRoute
  TenXLeapModuleRoute: typeof TenXLeapModuleRoute
  TenXLeapReviewRoute: typeof TenXLeapReviewRoute
  TenXLeapUnlockRoute: typeof TenXLeapUnlockRoute
  DashIndexRoute: typeof DashIndexRoute
  LeapIndexRoute: typeof LeapIndexRoute
  OperatingManualIndexRoute: typeof OperatingManualIndexRoute
  PrisonBreakIndexRoute: typeof PrisonBreakIndexRoute
  RareBreedClubIndexRoute: typeof RareBreedClubIndexRoute
  TenXLeapIndexRoute: typeof TenXLeapIndexRoute
  LeapInstallationsIdRoute: typeof LeapInstallationsIdRoute
  LeapInstallationsIndexRoute: typeof LeapInstallationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zone-of-genius-code': {
      id: '/zone-of-genius-code'
      path: '/zone-of-genius-code'
      fullPath: '/zone-of-genius-code'
      preLoaderRoute: typeof ZoneOfGeniusCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-library': {
      id: '/voice-library'
      path: '/voice-library'
      fullPath: '/voice-library'
      preLoaderRoute: typeof VoiceLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rare-breed-operating-manual': {
      id: '/rare-breed-operating-manual'
      path: '/rare-breed-operating-manual'
      fullPath: '/rare-breed-operating-manual'
      preLoaderRoute: typeof RareBreedOperatingManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metamorphosis': {
      id: '/metamorphosis'
      path: '/metamorphosis'
      fullPath: '/metamorphosis'
      preLoaderRoute: typeof MetamorphosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grant-access': {
      id: '/grant-access'
      path: '/grant-access'
      fullPath: '/grant-access'
      preLoaderRoute: typeof GrantAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ten-x-leap/': {
      id: '/ten-x-leap/'
      path: '/ten-x-leap'
      fullPath: '/ten-x-leap/'
      preLoaderRoute: typeof TenXLeapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rare-breed-club/': {
      id: '/rare-breed-club/'
      path: '/rare-breed-club'
      fullPath: '/rare-breed-club/'
      preLoaderRoute: typeof RareBreedClubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prison-break/': {
      id: '/prison-break/'
      path: '/prison-break'
      fullPath: '/prison-break/'
      preLoaderRoute: typeof PrisonBreakIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operating-manual/': {
      id: '/operating-manual/'
      path: '/operating-manual'
      fullPath: '/operating-manual/'
      preLoaderRoute: typeof OperatingManualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/': {
      id: '/leap/'
      path: '/leap'
      fullPath: '/leap/'
      preLoaderRoute: typeof LeapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/dash'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ten-x-leap/unlock': {
      id: '/ten-x-leap/unlock'
      path: '/ten-x-leap/unlock'
      fullPath: '/ten-x-leap/unlock'
      preLoaderRoute: typeof TenXLeapUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ten-x-leap/review': {
      id: '/ten-x-leap/review'
      path: '/ten-x-leap/review'
      fullPath: '/ten-x-leap/review'
      preLoaderRoute: typeof TenXLeapReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ten-x-leap/$module': {
      id: '/ten-x-leap/$module'
      path: '/ten-x-leap/$module'
      fullPath: '/ten-x-leap/$module'
      preLoaderRoute: typeof TenXLeapModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rare-breed-club/$builder': {
      id: '/rare-breed-club/$builder'
      path: '/rare-breed-club/$builder'
      fullPath: '/rare-breed-club/$builder'
      preLoaderRoute: typeof RareBreedClubBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prison-break/$module': {
      id: '/prison-break/$module'
      path: '/prison-break/$module'
      fullPath: '/prison-break/$module'
      preLoaderRoute: typeof PrisonBreakModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/weekly-audit': {
      id: '/leap/weekly-audit'
      path: '/leap/weekly-audit'
      fullPath: '/leap/weekly-audit'
      preLoaderRoute: typeof LeapWeeklyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/updates': {
      id: '/leap/updates'
      path: '/leap/updates'
      fullPath: '/leap/updates'
      preLoaderRoute: typeof LeapUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/os': {
      id: '/leap/os'
      path: '/leap/os'
      fullPath: '/leap/os'
      preLoaderRoute: typeof LeapOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/decision-filter': {
      id: '/leap/decision-filter'
      path: '/leap/decision-filter'
      fullPath: '/leap/decision-filter'
      preLoaderRoute: typeof LeapDecisionFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/constitution': {
      id: '/leap/constitution'
      path: '/leap/constitution'
      fullPath: '/leap/constitution'
      preLoaderRoute: typeof LeapConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/installations/': {
      id: '/leap/installations/'
      path: '/leap/installations'
      fullPath: '/leap/installations/'
      preLoaderRoute: typeof LeapInstallationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/installations/$id': {
      id: '/leap/installations/$id'
      path: '/leap/installations/$id'
      fullPath: '/leap/installations/$id'
      preLoaderRoute: typeof LeapInstallationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  GrantAccessRoute: GrantAccessRoute,
  LoginRoute: LoginRoute,
  MetamorphosisRoute: MetamorphosisRoute,
  RareBreedOperatingManualRoute: RareBreedOperatingManualRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  VoiceLibraryRoute: VoiceLibraryRoute,
  ZoneOfGeniusCodeRoute: ZoneOfGeniusCodeRoute,
  LeapConstitutionRoute: LeapConstitutionRoute,
  LeapDecisionFilterRoute: LeapDecisionFilterRoute,
  LeapOsRoute: LeapOsRoute,
  LeapUpdatesRoute: LeapUpdatesRoute,
  LeapWeeklyAuditRoute: LeapWeeklyAuditRoute,
  PrisonBreakModuleRoute: PrisonBreakModuleRoute,
  RareBreedClubBuilderRoute: RareBreedClubBuilderRoute,
  TenXLeapModuleRoute: TenXLeapModuleRoute,
  TenXLeapReviewRoute: TenXLeapReviewRoute,
  TenXLeapUnlockRoute: TenXLeapUnlockRoute,
  DashIndexRoute: DashIndexRoute,
  LeapIndexRoute: LeapIndexRoute,
  OperatingManualIndexRoute: OperatingManualIndexRoute,
  PrisonBreakIndexRoute: PrisonBreakIndexRoute,
  RareBreedClubIndexRoute: RareBreedClubIndexRoute,
  TenXLeapIndexRoute: TenXLeapIndexRoute,
  LeapInstallationsIdRoute: LeapInstallationsIdRoute,
  LeapInstallationsIndexRoute: LeapInstallationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
