/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestKitchenRouteImport } from './routes/test-kitchen'
import { Route as SexyUnicornOfferRouteImport } from './routes/sexy-unicorn-offer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RainbowRoadsRouteImport } from './routes/rainbow-roads'
import { Route as MetamorphosisRouteImport } from './routes/metamorphosis'
import { Route as MagicGumdropRouteImport } from './routes/magic-gumdrop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BrandUnicornRouteImport } from './routes/brand-unicorn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenXLeapIndexRouteImport } from './routes/ten-x-leap.index'
import { Route as RareBreedClubIndexRouteImport } from './routes/rare-breed-club.index'
import { Route as PrisonBreakIndexRouteImport } from './routes/prison-break.index'
import { Route as OperatingManualIndexRouteImport } from './routes/operating-manual.index'
import { Route as LeapIndexRouteImport } from './routes/leap.index'
import { Route as GumdropTrailsIndexRouteImport } from './routes/gumdrop-trails.index'
import { Route as DashIndexRouteImport } from './routes/dash.index'
import { Route as TenXLeapModuleRouteImport } from './routes/ten-x-leap.$module'
import { Route as RareBreedClubBuilderRouteImport } from './routes/rare-breed-club.$builder'
import { Route as PrisonBreakModuleRouteImport } from './routes/prison-break.$module'
import { Route as LeapWeeklyAuditRouteImport } from './routes/leap.weekly-audit'
import { Route as LeapUpdatesRouteImport } from './routes/leap.updates'
import { Route as LeapOsRouteImport } from './routes/leap.os'
import { Route as LeapDecisionFilterRouteImport } from './routes/leap.decision-filter'
import { Route as LeapConstitutionRouteImport } from './routes/leap.constitution'
import { Route as GumdropTrailsIdRouteImport } from './routes/gumdrop-trails.$id'
import { Route as LeapInstallationsIndexRouteImport } from './routes/leap.installations.index'
import { Route as LeapInstallationsIdRouteImport } from './routes/leap.installations.$id'

const TestKitchenRoute = TestKitchenRouteImport.update({
  id: '/test-kitchen',
  path: '/test-kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const SexyUnicornOfferRoute = SexyUnicornOfferRouteImport.update({
  id: '/sexy-unicorn-offer',
  path: '/sexy-unicorn-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RainbowRoadsRoute = RainbowRoadsRouteImport.update({
  id: '/rainbow-roads',
  path: '/rainbow-roads',
  getParentRoute: () => rootRouteImport,
} as any)
const MetamorphosisRoute = MetamorphosisRouteImport.update({
  id: '/metamorphosis',
  path: '/metamorphosis',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicGumdropRoute = MagicGumdropRouteImport.update({
  id: '/magic-gumdrop',
  path: '/magic-gumdrop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandUnicornRoute = BrandUnicornRouteImport.update({
  id: '/brand-unicorn',
  path: '/brand-unicorn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenXLeapIndexRoute = TenXLeapIndexRouteImport.update({
  id: '/ten-x-leap/',
  path: '/ten-x-leap/',
  getParentRoute: () => rootRouteImport,
} as any)
const RareBreedClubIndexRoute = RareBreedClubIndexRouteImport.update({
  id: '/rare-breed-club/',
  path: '/rare-breed-club/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrisonBreakIndexRoute = PrisonBreakIndexRouteImport.update({
  id: '/prison-break/',
  path: '/prison-break/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatingManualIndexRoute = OperatingManualIndexRouteImport.update({
  id: '/operating-manual/',
  path: '/operating-manual/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapIndexRoute = LeapIndexRouteImport.update({
  id: '/leap/',
  path: '/leap/',
  getParentRoute: () => rootRouteImport,
} as any)
const GumdropTrailsIndexRoute = GumdropTrailsIndexRouteImport.update({
  id: '/gumdrop-trails/',
  path: '/gumdrop-trails/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/dash/',
  path: '/dash/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenXLeapModuleRoute = TenXLeapModuleRouteImport.update({
  id: '/ten-x-leap/$module',
  path: '/ten-x-leap/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const RareBreedClubBuilderRoute = RareBreedClubBuilderRouteImport.update({
  id: '/rare-breed-club/$builder',
  path: '/rare-breed-club/$builder',
  getParentRoute: () => rootRouteImport,
} as any)
const PrisonBreakModuleRoute = PrisonBreakModuleRouteImport.update({
  id: '/prison-break/$module',
  path: '/prison-break/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapWeeklyAuditRoute = LeapWeeklyAuditRouteImport.update({
  id: '/leap/weekly-audit',
  path: '/leap/weekly-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapUpdatesRoute = LeapUpdatesRouteImport.update({
  id: '/leap/updates',
  path: '/leap/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapOsRoute = LeapOsRouteImport.update({
  id: '/leap/os',
  path: '/leap/os',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapDecisionFilterRoute = LeapDecisionFilterRouteImport.update({
  id: '/leap/decision-filter',
  path: '/leap/decision-filter',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapConstitutionRoute = LeapConstitutionRouteImport.update({
  id: '/leap/constitution',
  path: '/leap/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const GumdropTrailsIdRoute = GumdropTrailsIdRouteImport.update({
  id: '/gumdrop-trails/$id',
  path: '/gumdrop-trails/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapInstallationsIndexRoute = LeapInstallationsIndexRouteImport.update({
  id: '/leap/installations/',
  path: '/leap/installations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeapInstallationsIdRoute = LeapInstallationsIdRouteImport.update({
  id: '/leap/installations/$id',
  path: '/leap/installations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-unicorn': typeof BrandUnicornRoute
  '/login': typeof LoginRoute
  '/magic-gumdrop': typeof MagicGumdropRoute
  '/metamorphosis': typeof MetamorphosisRoute
  '/rainbow-roads': typeof RainbowRoadsRoute
  '/settings': typeof SettingsRoute
  '/sexy-unicorn-offer': typeof SexyUnicornOfferRoute
  '/test-kitchen': typeof TestKitchenRoute
  '/gumdrop-trails/$id': typeof GumdropTrailsIdRoute
  '/leap/constitution': typeof LeapConstitutionRoute
  '/leap/decision-filter': typeof LeapDecisionFilterRoute
  '/leap/os': typeof LeapOsRoute
  '/leap/updates': typeof LeapUpdatesRoute
  '/leap/weekly-audit': typeof LeapWeeklyAuditRoute
  '/prison-break/$module': typeof PrisonBreakModuleRoute
  '/rare-breed-club/$builder': typeof RareBreedClubBuilderRoute
  '/ten-x-leap/$module': typeof TenXLeapModuleRoute
  '/dash/': typeof DashIndexRoute
  '/gumdrop-trails/': typeof GumdropTrailsIndexRoute
  '/leap/': typeof LeapIndexRoute
  '/operating-manual/': typeof OperatingManualIndexRoute
  '/prison-break/': typeof PrisonBreakIndexRoute
  '/rare-breed-club/': typeof RareBreedClubIndexRoute
  '/ten-x-leap/': typeof TenXLeapIndexRoute
  '/leap/installations/$id': typeof LeapInstallationsIdRoute
  '/leap/installations/': typeof LeapInstallationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-unicorn': typeof BrandUnicornRoute
  '/login': typeof LoginRoute
  '/magic-gumdrop': typeof MagicGumdropRoute
  '/metamorphosis': typeof MetamorphosisRoute
  '/rainbow-roads': typeof RainbowRoadsRoute
  '/settings': typeof SettingsRoute
  '/sexy-unicorn-offer': typeof SexyUnicornOfferRoute
  '/test-kitchen': typeof TestKitchenRoute
  '/gumdrop-trails/$id': typeof GumdropTrailsIdRoute
  '/leap/constitution': typeof LeapConstitutionRoute
  '/leap/decision-filter': typeof LeapDecisionFilterRoute
  '/leap/os': typeof LeapOsRoute
  '/leap/updates': typeof LeapUpdatesRoute
  '/leap/weekly-audit': typeof LeapWeeklyAuditRoute
  '/prison-break/$module': typeof PrisonBreakModuleRoute
  '/rare-breed-club/$builder': typeof RareBreedClubBuilderRoute
  '/ten-x-leap/$module': typeof TenXLeapModuleRoute
  '/dash': typeof DashIndexRoute
  '/gumdrop-trails': typeof GumdropTrailsIndexRoute
  '/leap': typeof LeapIndexRoute
  '/operating-manual': typeof OperatingManualIndexRoute
  '/prison-break': typeof PrisonBreakIndexRoute
  '/rare-breed-club': typeof RareBreedClubIndexRoute
  '/ten-x-leap': typeof TenXLeapIndexRoute
  '/leap/installations/$id': typeof LeapInstallationsIdRoute
  '/leap/installations': typeof LeapInstallationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-unicorn': typeof BrandUnicornRoute
  '/login': typeof LoginRoute
  '/magic-gumdrop': typeof MagicGumdropRoute
  '/metamorphosis': typeof MetamorphosisRoute
  '/rainbow-roads': typeof RainbowRoadsRoute
  '/settings': typeof SettingsRoute
  '/sexy-unicorn-offer': typeof SexyUnicornOfferRoute
  '/test-kitchen': typeof TestKitchenRoute
  '/gumdrop-trails/$id': typeof GumdropTrailsIdRoute
  '/leap/constitution': typeof LeapConstitutionRoute
  '/leap/decision-filter': typeof LeapDecisionFilterRoute
  '/leap/os': typeof LeapOsRoute
  '/leap/updates': typeof LeapUpdatesRoute
  '/leap/weekly-audit': typeof LeapWeeklyAuditRoute
  '/prison-break/$module': typeof PrisonBreakModuleRoute
  '/rare-breed-club/$builder': typeof RareBreedClubBuilderRoute
  '/ten-x-leap/$module': typeof TenXLeapModuleRoute
  '/dash/': typeof DashIndexRoute
  '/gumdrop-trails/': typeof GumdropTrailsIndexRoute
  '/leap/': typeof LeapIndexRoute
  '/operating-manual/': typeof OperatingManualIndexRoute
  '/prison-break/': typeof PrisonBreakIndexRoute
  '/rare-breed-club/': typeof RareBreedClubIndexRoute
  '/ten-x-leap/': typeof TenXLeapIndexRoute
  '/leap/installations/$id': typeof LeapInstallationsIdRoute
  '/leap/installations/': typeof LeapInstallationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-unicorn'
    | '/login'
    | '/magic-gumdrop'
    | '/metamorphosis'
    | '/rainbow-roads'
    | '/settings'
    | '/sexy-unicorn-offer'
    | '/test-kitchen'
    | '/gumdrop-trails/$id'
    | '/leap/constitution'
    | '/leap/decision-filter'
    | '/leap/os'
    | '/leap/updates'
    | '/leap/weekly-audit'
    | '/prison-break/$module'
    | '/rare-breed-club/$builder'
    | '/ten-x-leap/$module'
    | '/dash/'
    | '/gumdrop-trails/'
    | '/leap/'
    | '/operating-manual/'
    | '/prison-break/'
    | '/rare-breed-club/'
    | '/ten-x-leap/'
    | '/leap/installations/$id'
    | '/leap/installations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-unicorn'
    | '/login'
    | '/magic-gumdrop'
    | '/metamorphosis'
    | '/rainbow-roads'
    | '/settings'
    | '/sexy-unicorn-offer'
    | '/test-kitchen'
    | '/gumdrop-trails/$id'
    | '/leap/constitution'
    | '/leap/decision-filter'
    | '/leap/os'
    | '/leap/updates'
    | '/leap/weekly-audit'
    | '/prison-break/$module'
    | '/rare-breed-club/$builder'
    | '/ten-x-leap/$module'
    | '/dash'
    | '/gumdrop-trails'
    | '/leap'
    | '/operating-manual'
    | '/prison-break'
    | '/rare-breed-club'
    | '/ten-x-leap'
    | '/leap/installations/$id'
    | '/leap/installations'
  id:
    | '__root__'
    | '/'
    | '/brand-unicorn'
    | '/login'
    | '/magic-gumdrop'
    | '/metamorphosis'
    | '/rainbow-roads'
    | '/settings'
    | '/sexy-unicorn-offer'
    | '/test-kitchen'
    | '/gumdrop-trails/$id'
    | '/leap/constitution'
    | '/leap/decision-filter'
    | '/leap/os'
    | '/leap/updates'
    | '/leap/weekly-audit'
    | '/prison-break/$module'
    | '/rare-breed-club/$builder'
    | '/ten-x-leap/$module'
    | '/dash/'
    | '/gumdrop-trails/'
    | '/leap/'
    | '/operating-manual/'
    | '/prison-break/'
    | '/rare-breed-club/'
    | '/ten-x-leap/'
    | '/leap/installations/$id'
    | '/leap/installations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandUnicornRoute: typeof BrandUnicornRoute
  LoginRoute: typeof LoginRoute
  MagicGumdropRoute: typeof MagicGumdropRoute
  MetamorphosisRoute: typeof MetamorphosisRoute
  RainbowRoadsRoute: typeof RainbowRoadsRoute
  SettingsRoute: typeof SettingsRoute
  SexyUnicornOfferRoute: typeof SexyUnicornOfferRoute
  TestKitchenRoute: typeof TestKitchenRoute
  GumdropTrailsIdRoute: typeof GumdropTrailsIdRoute
  LeapConstitutionRoute: typeof LeapConstitutionRoute
  LeapDecisionFilterRoute: typeof LeapDecisionFilterRoute
  LeapOsRoute: typeof LeapOsRoute
  LeapUpdatesRoute: typeof LeapUpdatesRoute
  LeapWeeklyAuditRoute: typeof LeapWeeklyAuditRoute
  PrisonBreakModuleRoute: typeof PrisonBreakModuleRoute
  RareBreedClubBuilderRoute: typeof RareBreedClubBuilderRoute
  TenXLeapModuleRoute: typeof TenXLeapModuleRoute
  DashIndexRoute: typeof DashIndexRoute
  GumdropTrailsIndexRoute: typeof GumdropTrailsIndexRoute
  LeapIndexRoute: typeof LeapIndexRoute
  OperatingManualIndexRoute: typeof OperatingManualIndexRoute
  PrisonBreakIndexRoute: typeof PrisonBreakIndexRoute
  RareBreedClubIndexRoute: typeof RareBreedClubIndexRoute
  TenXLeapIndexRoute: typeof TenXLeapIndexRoute
  LeapInstallationsIdRoute: typeof LeapInstallationsIdRoute
  LeapInstallationsIndexRoute: typeof LeapInstallationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-kitchen': {
      id: '/test-kitchen'
      path: '/test-kitchen'
      fullPath: '/test-kitchen'
      preLoaderRoute: typeof TestKitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sexy-unicorn-offer': {
      id: '/sexy-unicorn-offer'
      path: '/sexy-unicorn-offer'
      fullPath: '/sexy-unicorn-offer'
      preLoaderRoute: typeof SexyUnicornOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rainbow-roads': {
      id: '/rainbow-roads'
      path: '/rainbow-roads'
      fullPath: '/rainbow-roads'
      preLoaderRoute: typeof RainbowRoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metamorphosis': {
      id: '/metamorphosis'
      path: '/metamorphosis'
      fullPath: '/metamorphosis'
      preLoaderRoute: typeof MetamorphosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-gumdrop': {
      id: '/magic-gumdrop'
      path: '/magic-gumdrop'
      fullPath: '/magic-gumdrop'
      preLoaderRoute: typeof MagicGumdropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-unicorn': {
      id: '/brand-unicorn'
      path: '/brand-unicorn'
      fullPath: '/brand-unicorn'
      preLoaderRoute: typeof BrandUnicornRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ten-x-leap/': {
      id: '/ten-x-leap/'
      path: '/ten-x-leap'
      fullPath: '/ten-x-leap/'
      preLoaderRoute: typeof TenXLeapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rare-breed-club/': {
      id: '/rare-breed-club/'
      path: '/rare-breed-club'
      fullPath: '/rare-breed-club/'
      preLoaderRoute: typeof RareBreedClubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prison-break/': {
      id: '/prison-break/'
      path: '/prison-break'
      fullPath: '/prison-break/'
      preLoaderRoute: typeof PrisonBreakIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operating-manual/': {
      id: '/operating-manual/'
      path: '/operating-manual'
      fullPath: '/operating-manual/'
      preLoaderRoute: typeof OperatingManualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/': {
      id: '/leap/'
      path: '/leap'
      fullPath: '/leap/'
      preLoaderRoute: typeof LeapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gumdrop-trails/': {
      id: '/gumdrop-trails/'
      path: '/gumdrop-trails'
      fullPath: '/gumdrop-trails/'
      preLoaderRoute: typeof GumdropTrailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/dash'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ten-x-leap/$module': {
      id: '/ten-x-leap/$module'
      path: '/ten-x-leap/$module'
      fullPath: '/ten-x-leap/$module'
      preLoaderRoute: typeof TenXLeapModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rare-breed-club/$builder': {
      id: '/rare-breed-club/$builder'
      path: '/rare-breed-club/$builder'
      fullPath: '/rare-breed-club/$builder'
      preLoaderRoute: typeof RareBreedClubBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prison-break/$module': {
      id: '/prison-break/$module'
      path: '/prison-break/$module'
      fullPath: '/prison-break/$module'
      preLoaderRoute: typeof PrisonBreakModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/weekly-audit': {
      id: '/leap/weekly-audit'
      path: '/leap/weekly-audit'
      fullPath: '/leap/weekly-audit'
      preLoaderRoute: typeof LeapWeeklyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/updates': {
      id: '/leap/updates'
      path: '/leap/updates'
      fullPath: '/leap/updates'
      preLoaderRoute: typeof LeapUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/os': {
      id: '/leap/os'
      path: '/leap/os'
      fullPath: '/leap/os'
      preLoaderRoute: typeof LeapOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/decision-filter': {
      id: '/leap/decision-filter'
      path: '/leap/decision-filter'
      fullPath: '/leap/decision-filter'
      preLoaderRoute: typeof LeapDecisionFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/constitution': {
      id: '/leap/constitution'
      path: '/leap/constitution'
      fullPath: '/leap/constitution'
      preLoaderRoute: typeof LeapConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gumdrop-trails/$id': {
      id: '/gumdrop-trails/$id'
      path: '/gumdrop-trails/$id'
      fullPath: '/gumdrop-trails/$id'
      preLoaderRoute: typeof GumdropTrailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/installations/': {
      id: '/leap/installations/'
      path: '/leap/installations'
      fullPath: '/leap/installations/'
      preLoaderRoute: typeof LeapInstallationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leap/installations/$id': {
      id: '/leap/installations/$id'
      path: '/leap/installations/$id'
      fullPath: '/leap/installations/$id'
      preLoaderRoute: typeof LeapInstallationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandUnicornRoute: BrandUnicornRoute,
  LoginRoute: LoginRoute,
  MagicGumdropRoute: MagicGumdropRoute,
  MetamorphosisRoute: MetamorphosisRoute,
  RainbowRoadsRoute: RainbowRoadsRoute,
  SettingsRoute: SettingsRoute,
  SexyUnicornOfferRoute: SexyUnicornOfferRoute,
  TestKitchenRoute: TestKitchenRoute,
  GumdropTrailsIdRoute: GumdropTrailsIdRoute,
  LeapConstitutionRoute: LeapConstitutionRoute,
  LeapDecisionFilterRoute: LeapDecisionFilterRoute,
  LeapOsRoute: LeapOsRoute,
  LeapUpdatesRoute: LeapUpdatesRoute,
  LeapWeeklyAuditRoute: LeapWeeklyAuditRoute,
  PrisonBreakModuleRoute: PrisonBreakModuleRoute,
  RareBreedClubBuilderRoute: RareBreedClubBuilderRoute,
  TenXLeapModuleRoute: TenXLeapModuleRoute,
  DashIndexRoute: DashIndexRoute,
  GumdropTrailsIndexRoute: GumdropTrailsIndexRoute,
  LeapIndexRoute: LeapIndexRoute,
  OperatingManualIndexRoute: OperatingManualIndexRoute,
  PrisonBreakIndexRoute: PrisonBreakIndexRoute,
  RareBreedClubIndexRoute: RareBreedClubIndexRoute,
  TenXLeapIndexRoute: TenXLeapIndexRoute,
  LeapInstallationsIdRoute: LeapInstallationsIdRoute,
  LeapInstallationsIndexRoute: LeapInstallationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
